# SMCFan Build System
# Uses Swift Package Manager for building, adds signing and SMJobBless packaging

-include config.mk

# Validate configuration
ifndef CERT_ID
$(error CERT_ID not set. Copy config.mk.example to config.mk)
endif
ifndef HELPER_ID
$(error HELPER_ID not set. Copy config.mk.example to config.mk)
endif

# Directories
TEMPLATES_DIR = templates
GENERATED_DIR = generated
PRODUCTS_DIR = Products
APP_DIR = $(PRODUCTS_DIR)/SMCFanHelper.app
APP_CONTENTS = $(APP_DIR)/Contents
APP_MACOS = $(APP_CONTENTS)/MacOS
APP_RESOURCES = $(APP_CONTENTS)/Library/LaunchServices
APP_LAUNCH_DAEMONS = $(APP_CONTENTS)/Library/LaunchDaemons
APP_RESOURCES_DIR = $(APP_CONTENTS)/Resources
SPM_BUILD_DIR = .build/release

# SPM environment
SPM_ENV = HELPER_BUNDLE_ID=$(HELPER_ID)

.PHONY: all clean install test test-integration test-e2e help format lint

all: $(PRODUCTS_DIR)/smcfan $(APP_MACOS)/SMCFanInstaller $(APP_RESOURCES)/$(HELPER_ID) \
	$(APP_CONTENTS)/Info.plist $(APP_LAUNCH_DAEMONS)/$(HELPER_ID).plist \
	$(APP_MACOS)/$(HELPER_ID) sign-app

sign-app: $(APP_MACOS)/SMCFanInstaller $(APP_RESOURCES)/$(HELPER_ID) \
	$(APP_CONTENTS)/Info.plist \
	$(APP_LAUNCH_DAEMONS)/$(HELPER_ID).plist \
	$(APP_MACOS)/$(HELPER_ID)
	@codesign -s "$(CERT_ID)" -f --deep --timestamp "$(APP_DIR)"

# Generate Swift config file (injected into build)
$(GENERATED_DIR)/Config.generated.swift: config.mk
	@mkdir -p $(GENERATED_DIR)
	@echo '// Auto-generated by Makefile - do not edit' > $@
	@echo 'import Foundation' >> $@
	@echo '' >> $@
	@echo 'let _productionHelperBundleIDFromGenerated = "$(HELPER_ID)"' >> $@

# Build everything with SPM (after generating config)
.PHONY: spm-build
spm-build: $(GENERATED_DIR)/Config.generated.swift
	cp $(GENERATED_DIR)/Config.generated.swift Sources/common/Config.generated.swift
	$(SPM_ENV) swift build --configuration release -Xswiftc -DGENERATED_CONFIG
	rm -f Sources/common/Config.generated.swift

# Generate helper Info.plist
$(GENERATED_DIR)/helper-info.plist: $(TEMPLATES_DIR)/helper-info.plist.template config.mk
	@mkdir -p $(GENERATED_DIR)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' \
	    -e 's|@@TEAM_ID@@|$(TEAM_ID)|g' \
	    -e 's|@@INSTALLER_ID@@|$(INSTALLER_ID)|g' \
	    $< > $@

# Generate helper launchd.plist
$(GENERATED_DIR)/helper-launchd.plist: \
 $(TEMPLATES_DIR)/helper-launchd.plist.template config.mk
	@mkdir -p $(GENERATED_DIR)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' $< > $@

# Generate helper daemon.plist (SMAppService, in-bundle)
$(GENERATED_DIR)/helper-daemon.plist: \
 $(TEMPLATES_DIR)/helper-daemon.plist.template config.mk
	@mkdir -p $(GENERATED_DIR)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' \
	    -e 's|@@BUNDLE_ID_PREFIX@@|$(BUNDLE_ID_PREFIX)|g' $< > $@

# Copy and sign CLI
$(PRODUCTS_DIR)/smcfan: spm-build
	@mkdir -p $(PRODUCTS_DIR)
	@cp $(SPM_BUILD_DIR)/smcfan $@
	@codesign -s "$(CERT_ID)" -f --identifier smcfan --timestamp "$@"

# Copy and sign installer
$(APP_MACOS)/SMCFanInstaller: spm-build
	@mkdir -p $(APP_MACOS)
	@cp $(SPM_BUILD_DIR)/installer $@
	@xattr -cr "$@"
	@codesign -s "$(CERT_ID)" -f --identifier "$(INSTALLER_ID)" --timestamp "$@"

# Build helper with swiftc (for plist embedding - SPM doesn't support this)
HELPER_SOURCES = $(wildcard Sources/smcfanhelper/*.swift) \
	Sources/common/Config.swift Sources/common/SMCProtocol.swift

$(APP_RESOURCES)/$(HELPER_ID): $(HELPER_SOURCES) $(GENERATED_DIR)/Config.generated.swift \
	$(GENERATED_DIR)/helper-info.plist $(GENERATED_DIR)/helper-launchd.plist spm-build
	@mkdir -p $(APP_RESOURCES)
	# Build helper with swiftc to enable plist embedding (pure Swift - no C dependency)
	@swiftc -O -parse-as-library \
		-module-name smcfanhelper \
		-D GENERATED_CONFIG -D DIRECT_BUILD \
		Sources/common/Config.swift \
		Sources/common/SMCProtocol.swift \
		$(GENERATED_DIR)/Config.generated.swift \
		$(wildcard Sources/smcfanhelper/*.swift) \
		-framework Foundation -framework IOKit -framework CoreFoundation \
		-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __info_plist \
		-Xlinker $(GENERATED_DIR)/helper-info.plist \
		-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __launchd_plist \
		-Xlinker $(GENERATED_DIR)/helper-launchd.plist \
		-o $@
	@chmod +x "$@"
	@xattr -cr "$(APP_DIR)"
	@codesign -s "$(CERT_ID)" -f --options runtime --timestamp \
		--entitlements templates/helper.entitlements "$@"
	@cp $(GENERATED_DIR)/helper-launchd.plist "$(APP_RESOURCES)/$(HELPER_ID).plist"

# SMAppService (macOS 13+): plist in LaunchDaemons, helper in MacOS
$(APP_LAUNCH_DAEMONS)/$(HELPER_ID).plist: $(GENERATED_DIR)/helper-daemon.plist
	@mkdir -p $(APP_LAUNCH_DAEMONS)
	@cp $< "$@"

$(APP_MACOS)/$(HELPER_ID): $(APP_RESOURCES)/$(HELPER_ID)
	@cp "$<" "$@"

# Generate app Info.plist
$(APP_CONTENTS)/Info.plist: $(TEMPLATES_DIR)/Info.plist.template config.mk
	@mkdir -p $(APP_CONTENTS)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' \
	    -e 's|@@TEAM_ID@@|$(TEAM_ID)|g' \
	    -e 's|@@BUNDLE_ID_PREFIX@@|$(BUNDLE_ID_PREFIX)|g' \
	    $< > $@
	xattr -cr "$@"

# Install to /Applications
install: all
	sudo cp -r "$(APP_DIR)" /Applications/
	sudo chown -R root:wheel /Applications/SMCFanHelper.app

# Run unit tests
test:
	$(SPM_ENV) swift test --filter DataConversionTests

# Uninstall helper (for clean reinstall)
uninstall-helper:
	@echo "Uninstalling helper..."
	-sudo launchctl bootout system/$(HELPER_ID) 2>/dev/null
	-sudo rm -f /Library/LaunchDaemons/$(HELPER_ID).plist
	-sudo rm -f /Library/PrivilegedHelperTools/$(HELPER_ID)
	@echo "Helper uninstalled."

# Run integration tests (requires root and installed helper)
test-integration: all
	@swift build --product xcbeautify 2>/dev/null
	@echo "Resetting helper registration..."
	@sudo launchctl bootout system/$(HELPER_ID) 2>/dev/null || true
	@sudo sfltool resetbtm 2>/dev/null || true
	@sleep 2
	@echo "Installing helper to /Applications..."
	@sudo rm -rf /Applications/SMCFanHelper.app
	@sudo cp -R "$(APP_DIR)" /Applications/
	@sudo chown -R root:wheel /Applications/SMCFanHelper.app
	@echo "Running installer..."
	/Applications/SMCFanHelper.app/Contents/MacOS/SMCFanInstaller
	@echo "Waiting for daemon to start..."
	@for i in 1 2 3 4 5; do \
		if sudo launchctl list $(HELPER_ID) 2>/dev/null | grep -q "PID"; then \
			echo "Daemon started successfully"; \
			break; \
		fi; \
		sleep 1; \
	done
	@if ! sudo launchctl list $(HELPER_ID) 2>/dev/null | grep -q "PID"; then \
		echo "Error: Daemon failed to start"; \
		sudo launchctl list | grep $(HELPER_ID) || true; \
		exit 1; \
	fi
	@echo "Running tests as root..."
	@sudo -v
	@sudo script -q /dev/null bash -c '$(SPM_ENV) swift test --enable-code-coverage \
		--filter IntegrationTests' 2>&1 | script -q /dev/null bash -c 'stty -echo 2>/dev/null; \
		env -u NO_COLOR .build/debug/xcbeautify --is-ci'

# Generate coverage report from last test run
coverage-report:
	@PROFDATA=$$(find .build -name 'default.profdata' 2>/dev/null | head -1); \
	if [ -z "$$PROFDATA" ]; then \
		echo "No coverage data found. Run tests with coverage first."; exit 1; fi; \
	BINARY=$$(find .build -name 'SMCFanPackageTests.xctest' -type d 2>/dev/null | head -1)\
		/Contents/MacOS/SMCFanPackageTests; \
	xcrun llvm-cov report "$$BINARY" -instr-profile="$$PROFDATA" \
		-ignore-filename-regex='.build|Tests'

# Generate detailed coverage in lcov format
coverage-lcov:
	@PROFDATA=$$(find .build -name 'default.profdata' 2>/dev/null | head -1); \
	if [ -z "$$PROFDATA" ]; then \
		echo "No coverage data found. Run tests with coverage first."; exit 1; fi; \
	BINARY=$$(find .build -name 'SMCFanPackageTests.xctest' -type d 2>/dev/null | head -1)\
		/Contents/MacOS/SMCFanPackageTests; \
	xcrun llvm-cov export "$$BINARY" -instr-profile="$$PROFDATA" -format=lcov \
		-ignore-filename-regex='.build|Tests' > coverage.lcov; \
	echo "Coverage written to coverage.lcov"

# Run E2E test
test-e2e: all
	@echo "=== E2E Test: Fan Control ==="
	@echo ""
	@echo "Installing helper..."
	./$(APP_MACOS)/SMCFanInstaller
	@echo ""
	@echo "--- Part 1: Independent Fan Control ---"
	@echo ""
	@echo "1. Initial state:"
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "2. Set Fan 1 to 5000 RPM (Fan 0 should stay Auto, but wake to min):"
	./$(PRODUCTS_DIR)/smcfan set 1 5000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "3. Set Fan 0 to 6000 RPM (both fans now Manual):"
	./$(PRODUCTS_DIR)/smcfan set 0 6000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "4. Set Fan 1 to auto (Fan 0 should stay Manual):"
	./$(PRODUCTS_DIR)/smcfan auto 1
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "5. Set Fan 0 to auto (both should return to system mode):"
	./$(PRODUCTS_DIR)/smcfan auto 0
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "--- Part 2: Edge Cases ---"
	@echo ""
	@echo "6. Set Fan 0 to 0 RPM (manual stop - fan should stop completely):"
	./$(PRODUCTS_DIR)/smcfan set 0 0
	@sleep 2
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "7. Set Fan 0 to 1000 RPM (below reported min of ~2317):"
	./$(PRODUCTS_DIR)/smcfan set 0 1000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "8. Set Fan 0 to 10000 RPM (above reported max - should clamp to ~8500):"
	./$(PRODUCTS_DIR)/smcfan set 0 10000
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "9. Cleanup - return to auto:"
	./$(PRODUCTS_DIR)/smcfan auto 0
	./$(PRODUCTS_DIR)/smcfan auto 1
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "=== E2E Test Complete ==="

# Format code with swift-format
format:
	swift-format format --in-place --recursive Sources/ Tests/

# Lint code with swift-format
lint:
	swift-format lint --recursive Sources/ Tests/

# Clean
clean:
	rm -rf $(GENERATED_DIR) $(PRODUCTS_DIR) .build

# Help
help:
	@echo "SMCFan Build System (SPM + signing)"
	@echo ""
	@echo "Targets:"
	@echo "  all               - Build all components"
	@echo "  install           - Install to /Applications"
	@echo "  test              - Run unit tests"
	@echo "  test-integration  - Run integration tests (sudo, helper installed)"
	@echo "  test-e2e          - End-to-end test"
	@echo "  coverage-report   - Generate coverage report from last test run"
	@echo "  coverage-lcov     - Generate coverage in lcov format"
	@echo "  uninstall-helper - Uninstall privileged helper (for clean reinstall)"
	@echo "  format            - Format code with swift-format"
	@echo "  lint              - Lint code with swift-format"
	@echo "  clean             - Remove build artifacts"
