# SMCFan Build System
# Uses Swift Package Manager for building, adds signing and SMJobBless packaging

-include config.mk

# Validate configuration
ifndef CERT_ID
$(error CERT_ID not set. Copy config.mk.example to config.mk)
endif
ifndef HELPER_ID
$(error HELPER_ID not set. Copy config.mk.example to config.mk)
endif

# Directories
TEMPLATES_DIR = templates
GENERATED_DIR = generated
PRODUCTS_DIR = Products
APP_DIR = $(PRODUCTS_DIR)/SMCFanHelper.app
APP_CONTENTS = $(APP_DIR)/Contents
APP_MACOS = $(APP_CONTENTS)/MacOS
APP_RESOURCES = $(APP_CONTENTS)/Library/LaunchServices
SPM_BUILD_DIR = .build/release

# SPM environment
SPM_ENV = HELPER_BUNDLE_ID=$(HELPER_ID)

.PHONY: all clean install test test-e2e help format lint

all: $(PRODUCTS_DIR)/smcfan $(APP_MACOS)/SMCFanInstaller $(APP_RESOURCES)/$(HELPER_ID) $(APP_CONTENTS)/Info.plist

# Generate Swift config file (injected into build)
$(GENERATED_DIR)/Config.generated.swift: config.mk
	@mkdir -p $(GENERATED_DIR)
	@echo '// Auto-generated by Makefile - do not edit' > $@
	@echo 'import Foundation' >> $@
	@echo '' >> $@
	@echo 'let _productionHelperBundleIDFromGenerated = "$(HELPER_ID)"' >> $@

# Build everything with SPM (after generating config)
.PHONY: spm-build
spm-build: $(GENERATED_DIR)/Config.generated.swift
	cp $(GENERATED_DIR)/Config.generated.swift Sources/common/Config.generated.swift
	$(SPM_ENV) swift build --configuration release -Xswiftc -DGENERATED_CONFIG
	rm -f Sources/common/Config.generated.swift

# Generate helper Info.plist
$(GENERATED_DIR)/helper-info.plist: $(TEMPLATES_DIR)/helper-info.plist.template config.mk
	@mkdir -p $(GENERATED_DIR)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' \
	    -e 's|@@TEAM_ID@@|$(TEAM_ID)|g' \
	    -e 's|@@INSTALLER_ID@@|$(INSTALLER_ID)|g' \
	    $< > $@

# Generate helper launchd.plist
$(GENERATED_DIR)/helper-launchd.plist: $(TEMPLATES_DIR)/helper-launchd.plist.template config.mk
	@mkdir -p $(GENERATED_DIR)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' $< > $@

# Copy and sign CLI
$(PRODUCTS_DIR)/smcfan: spm-build
	@mkdir -p $(PRODUCTS_DIR)
	cp $(SPM_BUILD_DIR)/smcfan $@
	codesign -s "$(CERT_ID)" -f --identifier smcfan --timestamp "$@"

# Copy and sign installer
$(APP_MACOS)/SMCFanInstaller: spm-build
	@mkdir -p $(APP_MACOS)
	cp $(SPM_BUILD_DIR)/installer $@
	xattr -cr "$@"
	codesign -s "$(CERT_ID)" -f --identifier "$(INSTALLER_ID)" --timestamp "$@"

# Build helper with swiftc (for plist embedding - SPM doesn't support this)
HELPER_SOURCES = $(wildcard Sources/smcfanhelper/*.swift) Sources/common/Config.swift Sources/common/SMCProtocol.swift

$(APP_RESOURCES)/$(HELPER_ID): $(HELPER_SOURCES) $(GENERATED_DIR)/Config.generated.swift $(GENERATED_DIR)/helper-info.plist $(GENERATED_DIR)/helper-launchd.plist spm-build
	@mkdir -p $(APP_RESOURCES)
	# Build helper with swiftc to enable plist embedding (pure Swift - no C dependency)
	swiftc -O -parse-as-library \
		-module-name smcfanhelper \
		-D GENERATED_CONFIG -D DIRECT_BUILD \
		Sources/common/Config.swift \
		Sources/common/SMCProtocol.swift \
		$(GENERATED_DIR)/Config.generated.swift \
		$(wildcard Sources/smcfanhelper/*.swift) \
		-framework Foundation -framework IOKit -framework CoreFoundation \
		-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __info_plist -Xlinker $(GENERATED_DIR)/helper-info.plist \
		-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __launchd_plist -Xlinker $(GENERATED_DIR)/helper-launchd.plist \
		-o $@
	chmod +x "$@"
	xattr -cr "$(APP_DIR)"
	codesign -s "$(CERT_ID)" -f --options runtime --timestamp "$@"
	cp $(GENERATED_DIR)/helper-launchd.plist "$(APP_RESOURCES)/$(HELPER_ID).plist"

# Generate app Info.plist
$(APP_CONTENTS)/Info.plist: $(TEMPLATES_DIR)/Info.plist.template config.mk
	@mkdir -p $(APP_CONTENTS)
	sed -e 's|@@HELPER_ID@@|$(HELPER_ID)|g' \
	    -e 's|@@TEAM_ID@@|$(TEAM_ID)|g' \
	    -e 's|@@BUNDLE_ID_PREFIX@@|$(BUNDLE_ID_PREFIX)|g' \
	    $< > $@
	xattr -cr "$@"

# Install to /Applications
install: all
	sudo cp -r "$(APP_DIR)" /Applications/
	sudo chown -R root:wheel /Applications/SMCFanHelper.app

# Run unit tests
test:
	$(SPM_ENV) swift test --filter DataConversionTests

# Run E2E test
test-e2e: all
	@echo "=== E2E Test: Fan Control ==="
	@echo ""
	@echo "Installing helper..."
	./$(APP_MACOS)/SMCFanInstaller
	@echo ""
	@echo "--- Part 1: Independent Fan Control ---"
	@echo ""
	@echo "1. Initial state:"
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "2. Set Fan 1 to 5000 RPM (Fan 0 should stay Auto, but wake to min):"
	./$(PRODUCTS_DIR)/smcfan set 1 5000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "3. Set Fan 0 to 6000 RPM (both fans now Manual):"
	./$(PRODUCTS_DIR)/smcfan set 0 6000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "4. Set Fan 1 to auto (Fan 0 should stay Manual):"
	./$(PRODUCTS_DIR)/smcfan auto 1
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "5. Set Fan 0 to auto (both should return to system mode):"
	./$(PRODUCTS_DIR)/smcfan auto 0
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "--- Part 2: Edge Cases ---"
	@echo ""
	@echo "6. Set Fan 0 to 0 RPM (manual stop - fan should stop completely):"
	./$(PRODUCTS_DIR)/smcfan set 0 0
	@sleep 2
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "7. Set Fan 0 to 1000 RPM (below reported min of ~2317):"
	./$(PRODUCTS_DIR)/smcfan set 0 1000
	@sleep 3
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "8. Set Fan 0 to 10000 RPM (above reported max - should clamp to ~8500):"
	./$(PRODUCTS_DIR)/smcfan set 0 10000
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "9. Cleanup - return to auto:"
	./$(PRODUCTS_DIR)/smcfan auto 0
	./$(PRODUCTS_DIR)/smcfan auto 1
	@sleep 5
	./$(PRODUCTS_DIR)/smcfan list
	@echo ""
	@echo "=== E2E Test Complete ==="

# Format code with swift-format
format:
	swift-format format --in-place --recursive Sources/ Tests/

# Lint code with swift-format
lint:
	swift-format lint --recursive Sources/ Tests/

# Clean
clean:
	rm -rf $(GENERATED_DIR) $(PRODUCTS_DIR) .build

# Help
help:
	@echo "SMCFan Build System (SPM + signing)"
	@echo ""
	@echo "Targets:"
	@echo "  all       - Build all components"
	@echo "  install   - Install to /Applications"
	@echo "  test      - Run unit tests"
	@echo "  test-e2e  - End-to-end test"
	@echo "  format    - Format code with swift-format"
	@echo "  lint      - Lint code with swift-format"
	@echo "  clean     - Remove build artifacts"
